/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface EzModal {
    'close': () => void;
    'isOpen': boolean;
    'open': () => void;
  }
  interface EzModalAttributes extends StencilHTMLAttributes {
    'isOpen'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'EzModal': Components.EzModal;
  }

  interface StencilIntrinsicElements {
    'ez-modal': Components.EzModalAttributes;
  }


  interface HTMLEzModalElement extends Components.EzModal, HTMLStencilElement {}
  var HTMLEzModalElement: {
    prototype: HTMLEzModalElement;
    new (): HTMLEzModalElement;
  };

  interface HTMLElementTagNameMap {
    'ez-modal': HTMLEzModalElement
  }

  interface ElementTagNameMap {
    'ez-modal': HTMLEzModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
